apiVersion: cpe.cogadvisor.io/v1
kind: Benchmark
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cpe.cogadvisor.io/v1","kind":"Benchmark","metadata":{"annotations":{},"name":"coremark","namespace":"default"},"spec":{"benchmarkOperator":{"name":"none","namespace":"cpe-operator-system"},"benchmarkSpec":"backoffLimit: 0\ntemplate:\n  spec:\n    containers:\n      - name: coremark\n        image: {{ .image }}\n        command:\n        - sh\n        - -c\n        - ./coremark-{{ .thread }}thread{{if ne .thread \"1\"}}s{{end}}.exe\n    restartPolicy: Never\n","iterationSpec":{"configurations":[{"name":"image","values":["ghcr.io/sunya-ch/coremark:ubi"]}],"iterations":[{"name":"thread","values":["1","4","8","16","32"]}],"sequential":true},"parserKey":"coremark","repetition":3}}
  creationTimestamp: "2023-05-16T02:54:56Z"
  finalizers:
  - finalizers.benchmark.cpe.cogadvisor.io
  generation: 1
  name: coremark
  namespace: default
  resourceVersion: "2925802"
  uid: 36e96c65-c708-40c6-9958-21d74954227c
spec:
  benchmarkOperator:
    name: none
    namespace: cpe-operator-system
  benchmarkSpec: |
    backoffLimit: 0
    template:
      spec:
        containers:
          - name: coremark
            image: {{ .image }}
            command:
            - sh
            - -c
            - ./coremark-{{ .thread }}thread{{if ne .thread "1"}}s{{end}}.exe
        restartPolicy: Never
  iterationSpec:
    configurations:
    - name: image
      values:
      - ghcr.io/sunya-ch/coremark:ubi
    iterations:
    - name: thread
      values:
      - "1"
      - "4"
      - "8"
      - "16"
      - "32"
    sequential: true
  parserKey: coremark
  repetition: 3
status:
  bestResults:
  - build: init
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    performanceKey: iterations_per_sec
    performanceValue: "15046.991337"
    scenarioID: thread=1
  - build: init
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    performanceKey: iterations_per_sec
    performanceValue: "56772.946068"
    scenarioID: thread=4
  - build: init
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    performanceKey: iterations_per_sec
    performanceValue: "90156.821604"
    scenarioID: thread=8
  - build: init
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    performanceKey: iterations_per_sec
    performanceValue: "93264.550727"
    scenarioID: thread=16
  - build: init
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    performanceKey: iterations_per_sec
    performanceValue: "92323.461928"
    scenarioID: thread=32
  hash:
  - build: init
    hash: "1494354484"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "1"
    run: "0"
  - build: init
    hash: "3811854577"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "4"
    run: "0"
  - build: init
    hash: "2390653213"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "8"
    run: "0"
  - build: init
    hash: "3068050960"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "16"
    run: "0"
  - build: init
    hash: "1017675578"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "32"
    run: "0"
  - build: init
    hash: "1511132103"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "1"
    run: "1"
  - build: init
    hash: "3795076958"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "4"
    run: "1"
  - build: init
    hash: "2373875594"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "8"
    run: "1"
  - build: init
    hash: "3084828579"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "16"
    run: "1"
  - build: init
    hash: "1034453197"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "32"
    run: "1"
  - build: init
    hash: "1527909722"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "1"
    run: "2"
  - build: init
    hash: "3778299339"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "4"
    run: "2"
  - build: init
    hash: "2357097975"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "8"
    run: "2"
  - build: init
    hash: "3101606198"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "16"
    run: "2"
  - build: init
    hash: "984120340"
    iterations:
      image: ghcr.io/sunya-ch/coremark:ubi
      thread: "32"
    run: "2"
  jobCompleted: 15/15
  results:
  - build: init
    configID: image=ghcr.io/sunya-ch/coremark:ubi
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    repetitions:
    - job: coremark-cpeh-1494354484
      parseResult: '{"iterations_per_sec":[14955.507366],"total_sec":[13.373],"total_ticks":[13373]}'
      performanceKey: iterations_per_sec
      performanceValue: "14955.507366"
      pod: coremark-cpeh-1494354484-7kqrs
      pushedTime: 2023-05-16 02:55:20.910509935 +0000 UTC m=+34.523823194
      run: "0"
    - job: coremark-cpeh-1511132103
      parseResult: '{"iterations_per_sec":[15132.026935],"total_sec":[13.217],"total_ticks":[13217]}'
      performanceKey: iterations_per_sec
      performanceValue: "15132.026935"
      pod: coremark-cpeh-1511132103-6q5jn
      pushedTime: 2023-05-16 02:58:45.093557198 +0000 UTC m=+238.706870416
      run: "1"
    - job: coremark-cpeh-1527909722
      parseResult: '{"iterations_per_sec":[15053.439711],"total_sec":[13.286],"total_ticks":[13286]}'
      performanceKey: iterations_per_sec
      performanceValue: "15053.439711"
      pod: coremark-cpeh-1527909722-pgtfz
      pushedTime: 2023-05-16 03:02:11.873105702 +0000 UTC m=+445.486418967
      run: "2"
    scenarioID: thread=1
    scenarios:
      thread: "1"
  - build: init
    configID: image=ghcr.io/sunya-ch/coremark:ubi
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    repetitions:
    - job: coremark-cpeh-3811854577
      parseResult: '{"iterations_per_sec":[56152.172387],"total_sec":[14.247],"total_ticks":[14247]}'
      performanceKey: iterations_per_sec
      performanceValue: "56152.172387"
      pod: coremark-cpeh-3811854577-sv7xd
      pushedTime: 2023-05-16 02:55:45.983034066 +0000 UTC m=+59.596347312
      run: "0"
    - job: coremark-cpeh-3795076958
      parseResult: '{"iterations_per_sec":[56777.856636],"total_sec":[14.09],"total_ticks":[14090]}'
      performanceKey: iterations_per_sec
      performanceValue: "56777.856636"
      pod: coremark-cpeh-3795076958-p9nm5
      pushedTime: 2023-05-16 02:59:10.106090528 +0000 UTC m=+263.719403773
      run: "1"
    - job: coremark-cpeh-3778299339
      parseResult: '{"iterations_per_sec":[57388.809182],"total_sec":[13.94],"total_ticks":[13940]}'
      performanceKey: iterations_per_sec
      performanceValue: "57388.809182"
      pod: coremark-cpeh-3778299339-9vgvr
      pushedTime: 2023-05-16 03:02:37.013303587 +0000 UTC m=+470.626616814
      run: "2"
    scenarioID: thread=4
    scenarios:
      thread: "4"
  - build: init
    configID: image=ghcr.io/sunya-ch/coremark:ubi
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    repetitions:
    - job: coremark-cpeh-2390653213
      parseResult: '{"iterations_per_sec":[89806.915132],"total_sec":[17.816],"total_ticks":[17816]}'
      performanceKey: iterations_per_sec
      performanceValue: "89806.915132"
      pod: coremark-cpeh-2390653213-6w4bs
      pushedTime: 2023-05-16 02:56:15.234085299 +0000 UTC m=+88.847398516
      run: "0"
    - job: coremark-cpeh-2373875594
      parseResult: '{"iterations_per_sec":[90421.022888],"total_sec":[17.695],"total_ticks":[17695]}'
      performanceKey: iterations_per_sec
      performanceValue: "90421.022888"
      pod: coremark-cpeh-2373875594-x4fvc
      pushedTime: 2023-05-16 02:59:39.42549777 +0000 UTC m=+293.038811015
      run: "1"
    - job: coremark-cpeh-2357097975
      parseResult: '{"iterations_per_sec":[90242.526791],"total_sec":[17.73],"total_ticks":[17730]}'
      performanceKey: iterations_per_sec
      performanceValue: "90242.526791"
      pod: coremark-cpeh-2357097975-zppcj
      pushedTime: 2023-05-16 03:03:06.298890245 +0000 UTC m=+499.912203503
      run: "2"
    scenarioID: thread=8
    scenarios:
      thread: "8"
  - build: init
    configID: image=ghcr.io/sunya-ch/coremark:ubi
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    repetitions:
    - job: coremark-cpeh-3068050960
      parseResult: '{"iterations_per_sec":[93264.550727],"total_sec":[34.311],"total_ticks":[34311]}'
      performanceKey: iterations_per_sec
      performanceValue: "93264.550727"
      pod: coremark-cpeh-3068050960-nv24k
      pushedTime: 2023-05-16 02:57:00.824402988 +0000 UTC m=+134.437716210
      run: "0"
    - job: coremark-cpeh-3084828579
      parseResult: '{"iterations_per_sec":[89375.488772],"total_sec":[35.804],"total_ticks":[35804]}'
      performanceKey: iterations_per_sec
      performanceValue: "89375.488772"
      pod: coremark-cpeh-3084828579-d9962
      pushedTime: 2023-05-16 03:00:26.796528707 +0000 UTC m=+340.409841942
      run: "1"
    - job: coremark-cpeh-3101606198
      parseResult: '{"iterations_per_sec":[90625.885018],"total_sec":[35.31],"total_ticks":[35310]}'
      performanceKey: iterations_per_sec
      performanceValue: "90625.885018"
      pod: coremark-cpeh-3101606198-8km2k
      pushedTime: 2023-05-16 03:03:52.763837759 +0000 UTC m=+546.377150972
      run: "2"
    scenarioID: thread=16
    scenarios:
      thread: "16"
  - build: init
    configID: image=ghcr.io/sunya-ch/coremark:ubi
    configurations:
      image: ghcr.io/sunya-ch/coremark:ubi
    repetitions:
    - job: coremark-cpeh-1017675578
      parseResult: '{"iterations_per_sec":[92289.500627],"total_sec":[69.347],"total_ticks":[69347]}'
      performanceKey: iterations_per_sec
      performanceValue: "92289.500627"
      pod: coremark-cpeh-1017675578-k2mpb
      pushedTime: 2023-05-16 02:58:21.034590052 +0000 UTC m=+214.647903266
      run: "0"
    - job: coremark-cpeh-1034453197
      parseResult: '{"iterations_per_sec":[92357.423228],"total_sec":[69.296],"total_ticks":[69296]}'
      performanceKey: iterations_per_sec
      performanceValue: "92357.423228"
      pod: coremark-cpeh-1034453197-phklp
      pushedTime: 2023-05-16 03:01:46.804351128 +0000 UTC m=+420.417664343
      run: "1"
    - job: coremark-cpeh-984120340
      parseResult: '{"iterations_per_sec":[91889.330787],"total_sec":[69.649],"total_ticks":[69649]}'
      performanceKey: iterations_per_sec
      performanceValue: "91889.330787"
      pod: coremark-cpeh-984120340-xhnz7
      pushedTime: 2023-05-16 03:05:13.696019205 +0000 UTC m=+627.309332453
      run: "2"
    scenarioID: thread=32
    scenarios:
      thread: "32"
